blank_issues_enabled: false
contact_links:
  - name: "Awesome Selfhosted Data"
    url: "https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues"
    about: "Please submit your issues or suggestions to the Awesome-Selfhosted Data repository instead."
